# Nome da nossa action
name: Deploy

# roda a action a cada push
on:
    push:
        branches:
            - main

# Definir os Jobs
jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependecies
              run: npm install

            - name: Eslint
              run: npm run eslint:check

            - name: Prettier
              run: npm run prettier:check

            - name: Test
              run: npm run test
